# Generated by Django 3.0.8 on 2020-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='buyer',
            new_name='bidder',
        ),
        migrations.AddField(
            model_name='listing',
            name='buyer',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
