# Generated by Django 3.0.8 on 2020-07-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('seller', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('Applicances', 'Applicances'), ('Auto', 'Auto'), ('Clothing', 'Clothing'), ('Electrinics', 'Electrinics'), ('Home', 'Home'), ('Kitchen', 'Kitchen'), ('Misc', 'Misc'), ('Outdoors', 'Outdoors')], max_length=11)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=200)),
                ('post_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_item', to='auctions.Listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_item', to='auctions.Listings')),
            ],
        ),
    ]
