# Generated by Django 3.0.8 on 2020-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
