# Generated by Django 3.0.8 on 2020-07-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('wished_item', models.CharField(default='no item', max_length=64)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished', to='auctions.Listing')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
